### ISSUE TITLE
As a WHO employee we are responsible to create reports of all countries in the world

### ISSUE THREAD

**Issue by 40739022** [apkiys/devopsgrp5#1]
All the countries in the world organised by largest population to smallest.
All the countries in a continent organised by largest population to smallest.
All the countries in a region organised by largest population to smallest.

**Comment by HeatherTirivanhu98** [comment]
**Subtasks:**

- Write SQL query for all countries with name, population, region, and capital.

- Organize the countries in a tabular format.

- Integrate into the system for easy report generation.
