### ISSUE TITLE
As a WHO employee we are responsible to create reports of Populated Countries in the World

### ISSUE THREAD

**Issue by 40739022** [apkiys/devopsgrp5#2]
The top N populated countries in the world where N is provided by the user.
The top N populated countries in a continent where N is provided by the user.
The top N populated countries in a region where N is provided by the user.

**Comment by HeatherTirivanhu98** [comment]
**Subtasks:**

- Write SQL query to retrieve all countries by population.

- Sort countries by population size.

- Write SQL query for top N populated countries in world/continent/region

- Allow user input for N value.

- Output the report with the required fields.
