### ISSUE TITLE
As a WHO employee we are responsible to create reports of All Cities in the World

### ISSUE THREAD

**Issue by 40739022** [apkiys/devopsgrp5#3]
All the cities in the world organised by largest population to smallest.
All the cities in a continent organised by largest population to smallest.
All the cities in a region organised by largest population to smallest.
All the cities in a country organised by largest population to smallest.
All the cities in a district organised by largest population to smallest.
The top N populated cities in the world where N is provided by the user.
The top N populated cities in a continent where N is provided by the user.
The top N populated cities in a region where N is provided by the user.
The top N populated cities in a country where N is provided by the user.
The top N populated cities in a district where N is provided by the user.

**Comment by HeatherTirivanhu98** [comment]
**Subtasks:**

- Write SQL query to fetch all cities and their populations.

- Sort cities by population.

- Write SQL query for top N populated cities.

- Allow user input for N value.

- Display the results in a report interface.
