### ISSUE TITLE
As a WHO employee we are responsible to create reports of All Capital Cities in the World

### ISSUE THREAD

**Issue by 40739022** [apkiys/devopsgrp5#4]
All the capital cities in the world organised by largest population to smallest.
All the capital cities in a continent organised by largest population to smallest.
All the capital cities in a region organised by largest to smallest.
The top N populated capital cities in the world where N is provided by the user.
The top N populated capital cities in a continent where N is provided by the user.
The top N populated capital cities in a region where N is provided by the user.

**Comment by HeatherTirivanhu98** [comment]
**Subtasks:**

- Write SQL query to retrieve all capital cities.

- Organize capital cities by population (largest to smallest).

- Write SQL query for top N capital cities.

- Allow user input for N value.

- Integrate the query into the report system.
