### ISSUE TITLE
As a WHO employee we are responsible to create reports of People living in cities and not living in cities

### ISSUE THREAD

**Issue by 40739022** [apkiys/devopsgrp5#5]
The population of people, people living in cities, and people not living in cities in each continent.
The population of people, people living in cities, and people not living in cities in each region.
The population of people, people living in cities, and people not living in cities in each country.

**Comment by HeatherTirivanhu98** [comment]
**Subtasks**

- Create SQL query for urban vs. rural population in each continent.

- Create SQL query for urban vs. rural population in each region.

- Create SQL query for urban vs. rural population in each country.

- Fetch data for each country and calculate percentages.

- Integrate SQL query with the system and create a display template.
